name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MIX_ENV: test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        elixir: ['1.18']
        otp: ['27']

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmnl-dev

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-

    - name: Install Nerves bootstrap
      run: mix archive.install hex nerves_bootstrap --force

    - name: Install dependencies
      run: mix deps.get

    - name: Check code formatting
      run: mix format --check-formatted

    - name: Run tests
      run: mix test

    - name: Run Credo
      run: mix credo --strict

    - name: Cache PLT files
      uses: actions/cache@v4
      with:
        path: priv/plts
        key: ${{ runner.os }}-plt-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-plt-

    - name: Run Dialyzer
      run: mix dialyzer

    - name: Run basic integration test
      run: |
        mix run -e "
        MoodBot.Display.init_display()
        MoodBot.Display.clear()
        MoodBot.Display.show_mood(:happy)
        "